import type { BusTrip } from '../types';

export const MOCK_TRIPS: BusTrip[] = [
  {
    id: '1',
    busNumber: 'GJ-18-ZT-1831',
    busType: 'VOLVO',
    departureTime: '08:00',
    duration: '02:30',
    arrivalTime: '10:30',
    origin: 'Junagadh Busport',
    destination: 'Rajkot Busport',
    fare: 267.0,
    seatsAvailable: 45,
    route: ['Junagadh', 'Jetpur', 'Gondal', 'Rajkot'],
    source: 'GSRTC'
  },
  {
    id: '2',
    busNumber: 'GJ-06-BT-5047',
    busType: 'AC LUXURY',
    departureTime: '09:00',
    duration: '02:30',
    arrivalTime: '11:30',
    origin: 'Junagadh Busport',
    destination: 'Rajkot Busport',
    fare: 185.0,
    seatsAvailable: 39,
    route: ['Junagadh', 'Gondal', 'Rajkot'],
    source: 'GSRTC'
  },
  {
    id: '3',
    busNumber: 'GJ-12-ZT-9981',
    busType: 'EXPRESS',
    departureTime: '21:00',
    duration: '02:40',
    arrivalTime: '23:40',
    origin: 'Junagadh Busport',
    destination: 'Rajkot Busport',
    fare: 123.0,
    seatsAvailable: 42,
    route: ['Junagadh', 'Rajkot'],
    source: 'GSRTC'
  },
  {
    id: '4',
    busNumber: 'GJ-01-SM-1234',
    busType: 'SLEEPER',
    departureTime: '22:35',
    duration: '02:10',
    arrivalTime: '00:45',
    origin: 'Junagadh Busport',
    destination: 'Rajkot Busport',
    fare: 310.0,
    seatsAvailable: 12,
    route: ['Junagadh', 'Rajkot'],
    source: 'GSRTC'
  },
  {
    id: '5',
    busNumber: 'GJ-18-ZT-1832',
    busType: 'VOLVO',
    departureTime: '01:19',
    duration: '03:40',
    arrivalTime: '04:59',
    origin: 'Junagadh Busport',
    destination: 'Rajkot Busport',
    fare: 267.0,
    seatsAvailable: 41,
    route: ['Junagadh', 'Jetpur', 'Rajkot'],
    source: 'GSRTC'
  },
  {
    id: 'r1',
    busNumber: 'REDBUS-GS-101',
    busType: 'VOLVO',
    departureTime: '10:30',
    duration: '02:15',
    arrivalTime: '12:45',
    origin: 'Junagadh Busport',
    destination: 'Rajkot Busport',
    fare: 285.0,
    seatsAvailable: 15,
    route: ['Junagadh', 'Rajkot'],
    source: 'REDBUS'
  },
  {
    id: 'r2',
    busNumber: 'REDBUS-GS-202',
    busType: 'SLEEPER',
    departureTime: '23:55',
    duration: '02:30',
    arrivalTime: '02:25',
    origin: 'Junagadh Busport',
    destination: 'Rajkot Busport',
    fare: 340.0,
    seatsAvailable: 8,
    route: ['Junagadh', 'Rajkot'],
    source: 'REDBUS'
  }
];

export const STATIONS = [
  'Junagadh Busport',
  'Rajkot Busport',
  'Ahmedabad Central',
  'Baroda (Vadodara)',
  'Surat Central',
  'Bhavnagar',
  'Jamnagar',
  'Gandhinagar',
  'Anand',
  'Nadiad',
  'Mehsana',
  'Bhuj',
  'Somnath',
  'Dwarka',
  'Amreli',
  'Patan',
  'Palanpur',
  'Valsad',
  'Vapi',
  'Bharuch'
];
